
#include "bindings.h"
#include <microkit.h>

static const char cmdline[] = "";
// NOTE
// This is a symbol generated by "solo5-elftool" based on manifest.json
// which is a file that describes what devices this unikernel needs;
// This symbol is like the address to the manifest object that contains
// information about the devices.
extern const struct mft1_note __solo5_mft1_note;
// This is a local copy of the manifest note.
// @gt
// The ELF note is mapped read-only. Keep a writable copy of its manifest
// payload so that device bindings can populate runtime fields and mark
// entries as attached.
//
static struct mft *mft;
static union {
    uint64_t align;
    uint8_t bytes[sizeof(struct mft) +
            MFT_MAX_ENTRIES * sizeof(struct mft_entry)];
} mft_storage;


void platform_init(const void *arg)
{
    const struct mft *builtin_mft;
    size_t mft_size;

    (void)arg;
    assert(sddf_serial_init() == 0);
    assert(sddf_timer_init() == 0);

    // Retrieve the location & sizes of manifest;
    mft_get_builtin_mft1(&__solo5_mft1_note, &builtin_mft, &mft_size);
    if (mft_validate(builtin_mft, mft_size) != 0)
        PANIC("Invalid Solo5 application manifest", NULL);
    // Copy the manifest payload into the local buffer
    memcpy(mft_storage.bytes, builtin_mft, mft_size);
    // Initialise the local manifest payload copy
    mft = (struct mft *)mft_storage.bytes;
}

const char *platform_cmdline(void)
{
    return cmdline;
}

uint64_t platform_mem_size(void)
{
    return MICROKIT_HEAP_BASE + MICROKIT_HEAP_SIZE;
}

struct mft *microkit_manifest(void)
{
    return mft;
}

void platform_exit(int status, void *cookie __attribute__((unused)))
{
    // @gt ?? no_return, let the PD fault at a 'status' address
    uintptr_t fault_addr = (unsigned int)status;
#if defined(__aarch64__)
    __asm__ __volatile__("str xzr, [%0]" : : "r"(fault_addr) : "memory");
#elif defined(__x86_64__)
    __asm__ __volatile__("movl $0, (%0)" : : "r"(fault_addr) : "memory");
#else
#error Unsupported architecture
#endif
    __builtin_unreachable();
}

int platform_puts(const char *buf, int n)
{
    int written = sddf_serial_write(buf, n);

    /* Keep early initialisation and configuration failures observable. */
    if (written < 0) {
        for (int i = 0; i < n; i++)
            seL4_DebugPutChar(buf[i]);
        return n;
    }
    return written;
}

int platform_set_tls_base(uint64_t base)
{
#if defined(__x86_64__)
    /* seL4 enables CR4.FSGSBASE for native x86_64 PDs. */
    __asm__ __volatile__("wrfsbase %0" : : "r"(base));
    return 0;
#elif defined(__aarch64__)
    __asm__ __volatile__("msr tpidr_el0, %0" : : "r"(base));
    return 0;
#else
#error Unsupported architecture
#endif
}
